export const anaemia = `
<p style="margin-top:0pt; margin-bottom:20pt; line-height:125%;"><img src="/Walkers Logo.png" width="150" height="90" alt="Walkers Supermarket Logo" style="float: right; "><strong><u><span style="font-family:Poppins;font-weight:700;font-size:18pt;">ANAEMIA</span></u></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">What is it?</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">A condition caused by lack of red blood cells or haemoglobin for the body&rsquo;s needs. Red blood cells use haemoglobin to carry oxygen to your tissues and organs. Iron deficiency anaemia is the most common type.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Causes&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Anaemia can be caused by poor diet or an underlying health condition. There are three main ways that anaemia develops:</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Your body isn&rsquo;t making enough healthy red blood cells</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">This could be due to iron deficiency which is caused by lack of the mineral iron. Lack of or poor absorption of vitamin B12 and folate can result in the failure of producing enough red blood cells.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">There are many reasons why you may have a deficiency of iron, vitamin B12, or folate including pregnancy, diet (following a vegetarian or vegan diet increases risk of anaemia as animal products are the best source for iron and vitamin B12) or a condition that affects the absorption of nutrients from your bowel, such as Crohn&rsquo;s disease, coeliac disease or pernicious anaemia.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Your body breaks down your red blood cells too quickly</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Haemolytic anaemia can be triggered by an underlying health condition or by using medications such as penicillin and non-steroidal anti-inflammatory drugs.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">You&rsquo;ve lost a lot of blood</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">This might be sudden due to an injury or occur gradually over time such as heavy periods. Other reasons include peptic and stomach ulcers, piles, surgery or giving birth.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Other causes&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Some of the less common reasons why you may become anaemic are:</span></p>
<ul type="disc" style="margin:0pt; padding-left:0pt;">
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Having a condition that affects your immune system &ndash; such as cancer.</span></li>
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">An autoimmune condition such as rheumatoid arthritis or lupus.&nbsp;</span></li>
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">A genetic disorder such as thalassaemia or sickle cell disease.&nbsp;</span></li>
    <li style="margin-left:27.6pt; margin-bottom:8pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Chronic kidney disease&nbsp;</span></li>
</ul>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Symptoms&nbsp;</span></strong></p>
<ul type="disc" style="margin:0pt; padding-left:0pt;">
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Pale appearance</span></li>
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Tiredness and weakness</span></li>
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Not able to exercise as much as normal</span></li>
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Dizziness</span></li>
    <li style="margin-left:27.6pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Feeling faint</span></li>
    <li style="margin-left:27.6pt; margin-bottom:8pt;  line-height:125%; padding-left:8.4pt; font-family:serif; font-size:12pt;"><span style="font-family:Poppins;">Heart palpitations</span></li>
</ul>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">If you have any of these symptoms, contact your GP surgery for advice.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Diagnosis&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Your GP will ask about your symptoms and diet, so it is useful to keep a symptom and food diary. They may also ask you about any medications you&rsquo;re taking, recent illnesses and family history. A blood test may be all you need if it&rsquo;s obvious what&rsquo;s causing your anaemia.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Treatment</span></strong><span style="font-family:Poppins;">&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">By finding out the cause of your anaemia your doctor can help you get the right treatment.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Nutritional supplements and diet</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">You may need to take supplements if you&rsquo;re deficient in iron, folate, or vitamin B12. This could be for several months or for the rest of your life. Your GP may also give you some advice on how to get more iron, vitamin B12 or folate in your diet.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Iron -</span><strong><span style="font-family:Poppins;">&nbsp;</span></strong><span style="font-family:Poppins;">red meats, including&nbsp;</span><strong><span style="font-family:Poppins;">beef</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">lamb,&nbsp;</span></strong><span style="font-family:Poppins;">dark green vegetables including&nbsp;</span><strong><span style="font-family:Poppins;">spinach</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">cabbage</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">kale,&nbsp;</span></strong><span style="font-family:Poppins;">dried fruits such as&nbsp;</span><strong><span style="font-family:Poppins;">apricots</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">iron-fortified</span></strong><span style="font-family:Poppins;">&nbsp;</span><strong><span style="font-family:Poppins;">bread</span></strong><span style="font-family:Poppins;">.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Folate -&nbsp;</span><strong><span style="font-family:Poppins;">poultry</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">pork</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">shellfish</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">chickpeas</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">peas</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">brown rice</span></strong><span style="font-family:Poppins;">, green vegetables including&nbsp;</span><strong><span style="font-family:Poppins;">spinach</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">kale</span></strong><span style="font-family:Poppins;">, and&nbsp;</span><strong><span style="font-family:Poppins;">broccoli</span></strong><span style="font-family:Poppins;">, citrus fruits such as&nbsp;</span><strong><span style="font-family:Poppins;">oranges</span></strong><span style="font-family:Poppins;">&nbsp;and fortified foods such as&nbsp;</span><strong><span style="font-family:Poppins;">breakfast</span></strong><span style="font-family:Poppins;">&nbsp;</span><strong><span style="font-family:Poppins;">cereals</span></strong><span style="font-family:Poppins;">.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Vitamin B12 - red meats, including&nbsp;</span><strong><span style="font-family:Poppins;">beef</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">lamb</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">eggs</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">milk</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">other dairy products</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">fortified soy</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">bread</span></strong><span style="font-family:Poppins;">, and&nbsp;</span><strong><span style="font-family:Poppins;">cereal products</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">salmon</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">cod&nbsp;</span></strong><span style="font-family:Poppins;">and</span><strong><span style="font-family:Poppins;">&nbsp;nutritional yeast</span></strong><span style="font-family:Poppins;">.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Prevention of anaemia</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;  line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Eating a healthy, balanced diet will help but you cannot prevent many types of anaemia. Talk to your GP or pharmacist if you follow a vegan diet because they can provide advice about which supplements you might need to take.</span></p>
`;
