export const antiInflammatory = `

<p style="margin-top:0pt; margin-bottom:20pt; line-height:125%;"><img src="/Walkers Logo.png" width="160" height="90" alt="Walkers Supermarket Logo" style="float: right; "><strong><u><span style="font-family:Poppins;font-weight:700;font-size:18pt;">ANTI-INFLAMMATORY</span></u></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">What is inflammation?</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Inflammation is your body&rsquo;s reaction to foreign substances. It occurs to protect your body but can have a negative impact on your health if it long-term. Chronic (long-term) inflammation occurs in several diseases, including arthritis and diabetes. You can help reduce inflammation by changing your diet, as certain foods and drinks contain anti-inflammatory substances.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">What is an anti-inflammatory diet?</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">There is no strict anti-inflammatory diet, but incorporating certain anti-inflammatory foods into your meals can help control your inflammation to help relieve your symptoms if you have chronic joint pain and/or arthritis.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Avoid fried and processed foods, and have plenty of fresh&nbsp;</span><strong><span style="font-family:Poppins;">fruits</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">vegetables</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">wholegrains</span></strong><span style="font-family:Poppins;">, lean protein and foods rich in omega-3 fatty acids. Use herbs and spices instead of salt to not only add flavour but also for their inflammatory properties, especially&nbsp;</span><strong><span style="font-family:Poppins;">ginger&nbsp;</span></strong><span style="font-family:Poppins;">and&nbsp;</span><strong><span style="font-family:Poppins;">turmeric</span></strong><span style="font-family:Poppins;">.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Both the Mediterranean diet and the DASH (Dietary Approaches to Stop Hypertension) diet help to reduce inflammation.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">How do anti-inflammatory foods reduce inflammation?</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Environmental factors (pesticides and pollution) and lifestyle factors (alcohol, fried foods and smoking) increase the production of free radicals in the body. High levels of free radicals lead to oxidative stress &ndash; causing damage to your cells and is linked to diseases such as rheumatoid arthritis.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">The body produces antioxidants to counteract free radicals to stop them damaging cells but consuming a diet containing natural antioxidants can help. Rich dietary sources of antioxidants include&nbsp;</span><strong><span style="font-family:Poppins;">garlic</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">tomatoes</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">citrus fruits</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">kale</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">berries</span></strong><span style="font-family:Poppins;">. Anti-inflammatory foods include foods rich in antioxidants, nutrients and healthy fats.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:11pt;"><strong><span style="font-family:Poppins;">Anti-inflammatory foods&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Oily fish</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Oily fish are rich in omega-3 fatty acids, which can help reduce levels of proteins that cause inflammation, specifically C-reactive protein (CRP) and interleukin-6. Oily fish include&nbsp;</span><strong><span style="font-family:Poppins;">salmon</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">sardines</span></strong><span style="font-family:Poppins;">.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Fruits and vegetables</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Colourful fruits and vegetables are rich in antioxidants. Where possible, try to eat raw fruit and vegetables as cooking them reduces the nutrient and antioxidant levels.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Berries are rich in antioxidants such as&nbsp;</span><strong><span style="font-family:Poppins;">strawberries</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">blackberries</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">blueberries</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">cherries</span></strong><span style="font-family:Poppins;">. Eating&nbsp;</span><strong><span style="font-family:Poppins;">cherries</span></strong><span style="font-family:Poppins;">&nbsp;and drinking&nbsp;</span><strong><span style="font-family:Poppins;">cherry juice</span></strong><span style="font-family:Poppins;">&nbsp;can prevent gout flare-ups. Dark, leafy vegetables (</span><strong><span style="font-family:Poppins;">kale</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">spinach</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">pak choi</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">broccoli</span></strong><span style="font-family:Poppins;">),&nbsp;</span><strong><span style="font-family:Poppins;">red peppers</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">beetroot&nbsp;</span></strong><span style="font-family:Poppins;">are all rich in antioxidants.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Beans and legumes</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Beans and legumes are nutrient dense including antioxidants, fibre, folic acid, protein, iron, magnesium, potassium and zinc. Try a variety such as&nbsp;</span><strong><span style="font-family:Poppins;">lentils</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">red kidney beans</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">chickpeas</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">pinto beans</span></strong><span style="font-family:Poppins;">.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Nuts and seeds</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Rich sources of monounsaturated fatty acids (including omega 3 and 6), protein and fibre.&nbsp;</span><strong><span style="font-family:Poppins;">Almonds</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">pine nuts</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">flaxseed</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">walnuts</span></strong><span style="font-family:Poppins;">&nbsp;can be added to your breakfast or have as a snack.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Olive oil</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Olive oil</span></strong><span style="font-family:Poppins;">&nbsp;contains antioxidants, oleocanthal and monounsaturated fatty acids.&nbsp;</span><strong><span style="font-family:Poppins;">Extra virgin olive oil</span></strong><span style="font-family:Poppins;">&nbsp;contains more nutrients than regular olive oil as it is less refined and processed.</span><span style="font-family:Poppins;">&nbsp;&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Whole grains</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Replace refined grains (white bread and pasta etc) with whole grains as research has linked them to reducing inflammation. Whole grains include&nbsp;</span><strong><span style="font-family:Poppins;">oats</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">barley</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">bulgur</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">quinoa</span></strong><span style="font-family:Poppins;">&nbsp;</span><strong><span style="font-family:Poppins;">brown rice</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">buckwheat</span></strong><span style="font-family:Poppins;">.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Herbs and spices</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Herbs and spices with anti-inflammatory properties include&nbsp;</span><strong><span style="font-family:Poppins;">basil</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">cinnamon</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">chilli</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">garlic</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">ginger</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">rosemary</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">thyme</span></strong><span style="font-family:Poppins;">, and&nbsp;</span><strong><span style="font-family:Poppins;">turmeric</span></strong><span style="font-family:Poppins;">. Experiment with different combinations to boost the anti-inflammatory effects of your diet.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Probiotics and prebiotics</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Probiotic yoghurts</span></strong><span style="font-family:Poppins;">&nbsp;and fermented foods (such as&nbsp;</span><strong><span style="font-family:Poppins;">sauerkraut</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">kimchi</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">kefir</span></strong><span style="font-family:Poppins;">) contain live bacteria, which are beneficial for your body. These beneficial bacteria feed off plant fibres (prebiotics), sources include&nbsp;</span><strong><span style="font-family:Poppins;">leeks</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">onions</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">berries</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">peas</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">beans</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">bananas</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">oats</span></strong><span style="font-family:Poppins;">. You can reduce inflammation by eating more beneficial bacteria.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:11pt;"><strong><span style="font-family:Poppins;">Inflammatory foods to avoid</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Processed foods</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Highly processed foods tend to be inflammatory and contain high amounts of sugar, salt and trans fat. Foods to avoid include cakes, pastries, biscuits, ready meals and takeaways.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Vegetable oils</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">The body needs a balance between omega-3 and omega-6 fatty acids. Vegetable oils such as corn, soybean and sunflower have high levels of omega-6 fatty acids and should be replaced with olive or coconut oil to increase omega-3 fatty acids.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Alcohol</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Try to reduce your alcohol intake, particularly if you have rheumatoid arthritis. Drinking excessively increases levels of inflammatory proteins in your body such as CRP.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt;; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">&nbsp;</span></p>
`;
