export const lupus = `

<p style="margin-top:0pt; margin-bottom:20pt; line-height:125%;"><img src="/Walkers Logo.png" width="150" height="90" alt="Walkers Supermarket Logo" style="float: right; "><strong><u><span style="font-family:Poppins;font-weight:700;font-size:18pt;">LUPUS</span></u></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">What is it?</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Lupus is an autoimmune disease, which means the body&apos;s immune system attacks healthy parts of your body. It is more common in women than men, especially Black and Asian women.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Lupus and Diet</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">A healthy balanced diet is important, although some people would need to follow a specialised diet, for example, people with lupus nephritis (lupus affecting the kidneys) would need dietetic advice. Weight loss or weight gain can occur due to a thyroid issue, steroid treatment or fatigue. Fad-diets can be tempting but to lose weight and maintain your new weight you need to consume appropriate portions of varied and nutritious foods and exercise regularly.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Vitamin D supports the immune system and research studies have shown that people presenting severe lupus tend to have much lower vitamin D levels than those with a milder form. People with lupus are advised to take a daily vitamin D supplement. Vitamin D also known as the &lsquo;sunshine&rsquo; vitamin is mostly synthesised from sunlight on the skin, however you must protect yourself from UV exposure. Seek advice from your GP or consultant before taking any supplements as they can have a major impact on some medications, such as warfarin.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Several research studies have determined that lupus sufferers with a diet low in Omega-3 fatty acids had worse symptoms, higher cholesterol and atherosclerosis. Therefore, it is important for people who have lupus to supplement their diet with foods rich in omega-3 fatty acids as they have beneficial effects on cholesterol levels and inflammation. Oily fish (</span><strong><span style="font-family:Poppins;">salmon</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">sardines</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">mackerel</span></strong><span style="font-family:Poppins;">),&nbsp;</span><strong><span style="font-family:Poppins;">walnuts</span></strong><span style="font-family:Poppins;">,&nbsp;</span><strong><span style="font-family:Poppins;">tofu</span></strong><span style="font-family:Poppins;">&nbsp;and&nbsp;</span><strong><span style="font-family:Poppins;">flax seeds</span></strong><span style="font-family:Poppins;">&nbsp;are all rich sources of omega-3 fatty acids.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">Before drinking alcohol, first double-check with your doctor to make sure that any medications you are taking can potentiallt have more side effects if taken with alcohol.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">Foods to avoid?&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">People with lupus should avoid foods that contain excessive amounts of saturated fats, trans fats, sugar and salt,</span><span style="font-family:Poppins;">&nbsp;&nbsp;</span><span style="font-family:Poppins;">as they are at a higher riskm of coronary heart disease. Research has also identified alfalfa sprouts as another food to avoid, due to them containing high levels of the amino acid L-canavanine, that stimulates the immune system.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">You may find that you have problems processing some foods, described as food &ldquo;triggers.&rdquo; As they vary from person to person you speak to your GP and ask for a referral to a dietitian or an allergy specialist. It is useful to keep a log of what you eat and any symptoms, to identify any food &ldquo;triggers.&rdquo;&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><strong><span style="font-family:Poppins;">What to do during a flare up?&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt; line-height:125%; font-size:12pt;"><span style="font-family:Poppins;">During a flare up, you may struggle to stick with your healthy eating plan due to fatigue, weakness and pain. Do not be afraid to ask for help with preparing meals or acquiring special cooking equipment adapted to your needs. Using a slow cooker is suitable as there is minimal preparatio  involved and will allow time to rest before finishing and serving up the meal. On your good days, you could make extra meals by batch cooking so that you have nutritious, home-cooked meals ready to re-heat.&nbsp;</span></p>

`;
